style: fix visual bugs on the dropdown on the main feed
dailydotdev/apps pull request #1041
Opened 2022-06-21 13:58 UTC by AnishDe12020

## Changes
Fixes https://github.com/dailydotdev/daily/issues/586

### Describe what this PR does
- Fixes the text being cut off and box shadow on focus being cut off
![image](https://user-images.githubusercontent.com/63192115/174814065-81495c14-1375-4d2d-a1c2-29483d1e2bda.png)

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?
- [x] Does this not break anything in companion?

### Did you test the modified components media queries?
- [x] MobileL (420px)
- [x] Tablet (656px)
- [x] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari) 
- [x] Android

2022-06-21 14:38 UTC, rebelchris requested changes
Nice, thanks so much for this contribution 💪
I think we can make it a little bit more robust with the changes described.

2022-06-21 14:38 UTC, rebelchris commented on packages/shared/src/components/fields/Dropdown.tsx
> +        <span className="flex flex-1 truncate">{options[selectedIndex]}</span>
I think we need the margin right for the arrow icon.
Perhaps it's better to remove the parent container set width, not sure why we needed that.

2022-06-21 14:38 UTC, rebelchris commented on packages/shared/src/components/MainFeedLayout.tsx
> +      <div className="flex flex-row flex-wrap gap-4 items-center py-2 mr-px">
Looks like an overflow issue then?
Perhaps we can rather leverage border instead of the box-shadow for the border then?

2022-06-21 15:11 UTC, AnishDe12020 commented
Hey @rebelchris, I removed the explicit setting of the width but using border with it cause small layout shifts when clicking on the dropdown. After some googling, I figured out that I can use `inset` for our back shadow (so no overflow issue and no layout shifts). 

Do let me know if it is fine

2022-06-22 07:42 UTC, rebelchris requested changes
Almost there, I think if we settle for the described width's we are there.
The inset works fine it seems 💪

2022-06-22 07:42 UTC, rebelchris commented on packages/shared/src/components/MainFeedLayout.tsx
> -            className="w-44"
Sorry, my bad we use this to prevent layout shifts.

2022-06-22 07:42 UTC, rebelchris commented on packages/shared/src/components/MainFeedLayout.tsx
>            <Dropdown
This should work ;)
```suggestion
          <Dropdown className="w-44"
          
```

2022-06-23 05:27 UTC, AnishDe12020 commented
I have added back the width (`w-44` tailwind CSS class) to both the dropdowns. Also, the slightly higher width for the sorting dropdowns (10.5rem vs `w-44` that is 11rem) seems to make the recommended text appear completely :D

2022-06-23 07:16 UTC, rebelchris approved these changes
Perfect, thanks so much for this work @AnishDe12020 🥳

2022-06-23 07:19 UTC, merged