test: account pages
dailydotdev/apps pull request #1169
Opened 2022-09-01 06:18 UTC by sshanzel

## WIP

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-389 #done

2022-09-04 08:20 UTC, sshanzel commented
One of the awesome things about creating test cases is the opportunity to refactor the code. I centralized some calls to avoid unnecessary requests. Also fixed session verification process for linking accounts.

With that, I will branch out from this the code required for validating the linking/unlinking of social providers.

cc @rebelchris would love to hear what you think 🚢

2022-09-05 08:51 UTC, rebelchris requested changes
Wow impressive work overall!
Some minor comments, really love the refactors here

2022-09-05 08:51 UTC, rebelchris commented on packages/webapp/__tests__/AccountSecurityPage.tsx
> +  const params = {
We'll have to catch this flow now with the new (non-required) fields

2022-09-05 08:57 UTC, sshanzel commented on packages/shared/__tests__/fixture/auth.ts
>  import nock from 'nock';
These fixtures are used on other test suites (test suites in the shared components and the webapp) as well that's why I kept them here. For when a test suite requires any of the flow we have, we can use these data. WDYT?

2022-09-05 08:59 UTC, rebelchris commented on packages/shared/__tests__/fixture/auth.ts
>  import nock from 'nock';
Yeah the mocks are fine, thought I saw actual tests there as well, but don't see them now, so good to go.

2022-09-05 09:01 UTC, sshanzel commented on packages/webapp/__tests__/AccountOthersPage.tsx
> +const defaultLoggedUser: LoggedUser = {
Totally right! Let me refactor these ones.

2022-09-05 09:39 UTC, sshanzel commented on packages/webapp/__tests__/AccountSecurityPage.tsx
> +const defaultLoggedUser: LoggedUser = {
Can you check if the changes I made were acceptable? Or should I make changes to the user fixture to have the data I needed?

2022-09-05 09:58 UTC, rebelchris approved these changes
I'm happy with this, but it's up to you we can also move the fields to the defaultUser, just means we have to adjust other snapshots.

2022-09-05 10:07 UTC, sshanzel commented
> I'm happy with this, but it's up to you we can also move the fields to the defaultUser, just means we have to adjust other snapshots.

I think I will keep this change for now since the tests are specific to those fields. Thank you for the review! 🚢

2022-09-05 11:54 UTC, merged