fix: csrf issue by allowing refetch
dailydotdev/apps pull request #1201
Opened 2022-09-12 13:07 UTC by sshanzel

## Changes

### Describe what this PR does
- When the user has taken a very very long time before proceeding with the auth flow, the CSRF token could have expired. In order to refresh it, we are now allowing the refetch of the flow.
- Also applied it to cases where refetch was disabled.
- Applied a toast message for when CSRF token-related issues.
- I also experienced the some glitch, but not yet certain, that sometimes the flows are not working unless I clear the site's cache data.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-443 #done

2022-09-13 08:06 UTC, rebelchris requested changes

2022-09-13 08:17 UTC, sshanzel commented on packages/shared/src/hooks/useRegistration.ts
> +          return displayToast('An error occurred, kindly refresh the page.');
This issue kinda happens when the CSRF expired and the client has not re-fetched the flow. For this, the only way to refresh is to go outside and refocus, etc. or this, refreshing the page. WDYT?

Let me check with Graham as well with regards to the message.

2022-09-14 06:06 UTC, sshanzel commented
@rebelchris I have now updated the text based on the discussion in Slack. Would love to hear your thoughts.

2022-09-14 06:29 UTC, rebelchris approved these changes
Awesome, happy with this 🥳

2022-09-14 06:42 UTC, merged