feat: [modal migration] upvoted by
dailydotdev/apps pull request #1377
Opened 2022-11-16 08:39 UTC by el

## Changes

Also fixes issue with the close button size:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1488164/202130624-c6f13d98-c5b0-4dfd-a282-3344db2bdcb5.png">

2022-11-16 10:22 UTC, rebelchris requested changes
Some more generic to this one feedback:

- Pressing outside the modal doesn't close it for some reason
- When the list has the preloaders it actually shifts the layout (height of the modal)

2022-11-16 10:22 UTC, rebelchris commented on packages/shared/src/components/RecommendedMention.tsx
> +            'py-3 px-3 cursor-pointer',
```suggestion
            'p3 cursor-pointer',
```

2022-11-16 13:44 UTC, el commented
@rebelchris @sshanzel here is how it looks now:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/1488164/202196639-af377d9b-bde1-4bcd-a428-6abdbe194350.png">

2022-11-16 13:47 UTC, el commented on packages/shared/src/components/RecommendedMention.tsx
> +            'py-3 px-3 cursor-pointer',
Upps, it should be `p-3`

2022-11-17 07:57 UTC, merged

2022-11-17 07:59 UTC, rebelchris reviewed
It almost looks too big now compared to the one we have?
Also can we prioritised the backdrop close before pushing this live? (I don't want this to go live as it has high impact on users)