feat: [modal migration] shortcuts
dailydotdev/apps pull request #1385
Opened 2022-11-18 14:36 UTC by el

## Changes

<img width="903" alt="Screenshot 2022-11-18 at 17 22 41" src="https://user-images.githubusercontent.com/1488164/202729256-a289d9e6-cea7-487b-aeb6-5260f4fb60c3.png">
<img width="816" alt="Screenshot 2022-11-18 at 17 22 46" src="https://user-images.githubusercontent.com/1488164/202729274-887c657f-5a42-4597-9b76-cbc22cc81eb2.png">

2022-11-21 12:36 UTC, rebelchris requested changes

2022-11-21 12:36 UTC, rebelchris commented on packages/extension/src/newtab/ShortcutLinksModal.tsx
> +      <Modal.Footer justify={displayRevoke ? 'between' : 'end'}>
I changed this in a separate PR, which blocks this for now.

2022-11-21 12:46 UTC, sshanzel approved these changes
Other than what Chris has mentioned, the cleanup looks amazing to me. Always so satisfying to see every time a modal is converted ✨ ✨ ✨ 

With me approving, I think (and hope) merging is still blocked as change is requested by another reviewr. But let me test it now 😆

2022-11-21 13:08 UTC, rebelchris commented
Found one more concern, this is already broken, but let's fix it before merging this PR.

![Uploading Screenshot 2022-11-21 at 15.06.23.png…]()

2022-11-22 09:55 UTC, rebelchris commented
@sshanzel @el I also revamped the Most Visited sites modal as it was part of this PR.

Here is the new one:
![Screenshot 2022-11-22 at 11 51 53](https://user-images.githubusercontent.com/554874/203283425-b5696a8f-b8d4-443a-9cc3-bc344a7a488b.png)

2022-11-27 07:01 UTC, sshanzel approved these changes
Thanks for updating the accepting of permission modal as well! 🚢

2022-11-28 09:46 UTC, el commented
Thanks for taking care of this one @rebelchris  ❤️

2022-11-28 09:52 UTC, rebelchris approved these changes
Let's do it 🛳️

2022-11-28 09:57 UTC, merged