fix: refactor article to post copy
dailydotdev/apps pull request #1578
Opened 2023-02-03 16:47 UTC by rebelchris

## Changes

### Describe what this PR does
- Refactor `article` copy to `post`

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1017 #done

2023-02-04 07:57 UTC, idoshamun commented on packages/shared/src/components/post/PostContent.tsx
> +            title="Go to post"
This one sounds a bit funny worth double checking

2023-02-04 07:57 UTC, idoshamun commented on packages/shared/src/components/post/PostModalActions.tsx
> +          content="Read post"
This one as well

2023-02-04 07:58 UTC, idoshamun approved these changes

2023-02-06 05:51 UTC, sshanzel requested changes
Nice! Thanks for taking this on. I think there are still few left, just not sure if they should be kept.
- `ShareModal` the title is `Share article`.
- `sourceToMessage` in the `EnableNotification`.
- In the `PostToSquad` not sure what to do at line 71:  ```const title = `${post ? 'Share' : 'Post'} article`;```
- There is one in `AuthorStats` component.
- There is one in `PostsSection` component.
- The placeholder in `Comment.tsx`
- The `SelectArticle` component has many `article` words but not sure if they are intended.
- `/squads/utils.tsx` the `ModalState` is used as modal header.
- `SocialShare` last item has one.
- Some copies in the `featureManagement` file.

2023-02-06 07:02 UTC, rebelchris commented
@sshanzel Thanks, somehow those didn't show up in my search, modified those and 2 more.

2023-02-06 07:07 UTC, sshanzel approved these changes
Just the suggestions then I think we should be good to go! Nice catch on the user page! 🚢

2023-02-06 07:07 UTC, sshanzel commented on packages/shared/src/components/squads/SelectArticle.tsx
> +          <SquadTitleColor>an post</SquadTitleColor>
```suggestion
          <SquadTitleColor>a post</SquadTitleColor>
```

2023-02-06 07:07 UTC, sshanzel commented on packages/shared/src/components/squads/utils.tsx
> +  SelectArticle = 'Pick an post',
```suggestion
  SelectArticle = 'Pick a post',
```

2023-02-06 15:19 UTC, merged

2023-02-06 15:28 UTC, nimrodkra commented on packages/shared/src/components/modals/SubmitArticleModal.spec.tsx
> +  const btn = await screen.findByLabelText('Submit post');
Let's do it `Submit link` instead.

2023-02-06 15:29 UTC, nimrodkra commented on packages/shared/src/components/modals/SubmitArticleModal.spec.tsx
> +  const sent = 'You will be notified via email about the post request status';
Change: We will notify you about the post-submission status via email

2023-02-06 15:30 UTC, nimrodkra commented on packages/shared/src/components/modals/SubmitArticleModal.spec.tsx
> +  const btn = await screen.findByLabelText('Submit post');
Submit link

2023-02-06 15:30 UTC, nimrodkra commented on packages/shared/src/components/modals/SubmitArticleModal.spec.tsx
> +  const btn = await screen.findByLabelText('Submit post');
Submit link

2023-02-06 15:30 UTC, nimrodkra commented on packages/shared/src/components/modals/SubmitArticleModal.tsx
> +          We want you to submit posts that are well thought out, high value and
We want you to submit links that are well thought out...

2023-02-06 15:31 UTC, nimrodkra commented on packages/shared/src/components/modals/SubmitArticleModal.tsx
> +                title="You will be notified via email about the post request status"
We will notify you via email about the post submission status

2023-02-06 15:33 UTC, nimrodkra commented on packages/shared/src/lib/featureManagement.ts
> +    "We'll ask for extra permissions so we can show the companion directly on an post!",
We'll ask for extra permissions so we can show the companion directly on the original content!

2023-02-06 15:35 UTC, nimrodkra commented on packages/shared/src/components/squads/SelectArticle.tsx
> +            : 'Pick an post that you would like to discuss with the members of your Squad.'}
Pick n post that you would like to discuss with the members of your Squad.