fix: shared post card metadata
dailydotdev/apps pull request #1637
Opened 2023-02-24 05:29 UTC by sshanzel

## Changes

@rebelchris the build was failing due to some existing implementations that require updating.
Though instead of refactoring the whole component, I have instead wrapped the only usage that required the clamping. 

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1107 #done

2023-02-24 05:36 UTC, sshanzel commented
We have a test suite for this component and a case specific to the issue we suffered here, I wonder if there is any way we can replicate what we had here in a test environment. Has anyone tried it before? Like, be able to set some specific width on test environment for testing a component?

2023-02-24 07:49 UTC, rebelchris requested changes
This actually doesn't clamp it.

![Screenshot 2023-02-24 at 09 49 30](https://user-images.githubusercontent.com/554874/221122186-19940e98-a2ea-4218-8e7a-39120fb91b9e.png)

2023-02-24 08:55 UTC, sshanzel commented
@rebelchris oh, I didn't see that coming. Let me revert the revert quickly! And just fix the build 😅

2023-02-24 09:04 UTC, sshanzel commented
@rebelchris did it work for you locally? It doesn't seem to fix the initial concern on my local environment.

![image](https://user-images.githubusercontent.com/13744167/221136826-980c2965-8468-4320-aadf-dfb0fcfd2c8b.png)

2023-02-28 06:41 UTC, sshanzel commented
@rebelchris I can continue to debug this forward if you won't have time for it today. Just let me know 🙌

2023-02-28 12:48 UTC, sshanzel commented
@rebelchris I've realized the problem is with the separator taking a new line when rendered. So I thought of using the browser-supported text that is intended for separations like this. It is called `interpunct`. I think this is best to use than creating a div element just to replicate the behavior. The card should now look like below on normal content:

![image](https://user-images.githubusercontent.com/13744167/221858163-b3b65ebc-e3e3-407a-8146-276c285d0e2b.png)

Looks like this when clamped. Since the clamp is for a single line only, we need to trigger the breaking of words:
![image](https://user-images.githubusercontent.com/13744167/221858362-b3375501-b0dc-4e77-af1c-3dc82a551cb4.png)

2023-02-28 13:01 UTC, rebelchris approved these changes
@sshanzel Just one question, but nice find!
That's a good solution for this edge case.

2023-02-28 13:41 UTC, sshanzel commented on packages/shared/src/components/ConditionalWrapper.tsx
> +export interface ConditionalWrapperProps {
Oh, this was on some previous implementation. I can revert this back now. Thanks for the note!

2023-02-28 13:51 UTC, merged