fix: image on the edit welcome post is shouldn't be rounded
dailydotdev/apps pull request #1807
Opened 2023-05-15 14:05 UTC by TomDowling

## Changes
Removed the prop to make the image circular. I didn't find anywhere affected from removing this prop

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1361 #done

2023-05-15 14:32 UTC, rebelchris approved these changes

2023-05-15 14:35 UTC, sshanzel requested changes
We actually have to keep it depending on the type of comment box. This is called `ProfilePicture` but unfortunately being used by `Source` entity on some cases.

2023-05-16 06:54 UTC, rebelchris commented on packages/shared/src/components/modals/CommentBox.tsx
> +              rounded="full"
You can just make this line optional based on isComment, but is it the right evaluation? Not sure what it fires on.

2023-05-16 07:42 UTC, sshanzel requested changes
Just one last thing 🥳

2023-05-16 07:42 UTC, sshanzel commented on packages/shared/src/components/modals/CommentBox.tsx
> +          )}
I think their only difference is the property. I think we can just apply the condition from the property itself. WDYT?
```suggestion
          <ProfilePicture
            size="large"
            rounded={isComment && 'full'}
            user={{ image: authorImage, username: authorName }}
            nativeLazyLoading
          />
```

2023-05-16 07:53 UTC, sshanzel approved these changes
Way better with `undefined`! 🚀 🚀 🚀

2023-05-16 08:00 UTC, rebelchris approved these changes
Love it 🤙

2023-05-16 08:00 UTC, merged