feat: markdown input
dailydotdev/apps pull request #1820
Opened 2023-05-22 15:43 UTC by sshanzel

## Changes
As we add more and more features with Markdown editing, we've created the building blocks for adding new commands. We were able to reuse the generic function for textarea with both Link and Mention features. It would easily allow the implementation of bold, italic, etc. by adding literally a simple function like shown below:

```
const onBoldCommand = async (_, { word }) => {
    const getUsernameReplacement = () => ({ replacement: `__${word}__` });
    await replaceWord(textarea, selection, getUsernameReplacement, setInput);
  };

```

This is also in preparation for v7 where we will revamp the comment box where we will have a bit different layout than writing Freeform posts but the functionality will be almost the same. The `useMarkdownInput` hook should be easy to use as we did on `MarkdownInput`.

The current one we have for the comment box is very specific only to mentions and the processes won't be re-used to any of the new commands. As we can see now, the mention is just reusing the functions provided by what we have created in `textarea.ts`. Once we hit v7, we will delete the old hook `useUserMention`, and the parts along with it in the `elements.ts` file.

This is currently deployed in preview

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

2023-05-22 15:49 UTC, sshanzel commented
@idoshamun would love to get your opinion here as this is a bit heavy one.

2023-05-23 06:41 UTC, sshanzel commented on packages/shared/src/lib/textarea.ts
> +export const replaceWord = async (
This is where it all happens. There should not be too much change here in the future as its purpose is simple, to replace the word based on the parameters. The optional parameter is how to set the cursor position if the default behavior is not what you would expect.

2023-05-23 13:55 UTC, idoshamun requested changes
Oh wow that looks like huge amount of work! 👏 
Still requires some tweaks

2023-05-23 13:55 UTC, idoshamun commented on packages/shared/src/components/post/PostEngagements.tsx
> +      {/* TODO:: Revert this after testing phase */}
Need to be reverted I guess?

2023-05-23 13:57 UTC, sshanzel commented on packages/shared/src/lib/textarea.ts
> +export const replaceWord = async (
Agree with that. Let me see how we can break this down into pieces.

2023-05-23 13:59 UTC, sshanzel commented on packages/shared/src/lib/markdown.ts
> +const getUrlText = (content = '') => `[${content}](${urlText})`;
I was using it to have an easier reference of the length when we generate the offset but agree, this suggestion would make it simpler. I'll just create another variable with the exact expected offset with a proper name.

2023-05-24 06:04 UTC, idoshamun commented on packages/shared/src/lib/markdown.ts
> +const getUrlText = (content = '') => `[${content}](${urlText})`;
I didn't notice that. If this is the case you can keep it :)

2023-05-25 04:35 UTC, sshanzel commented
@idoshamun I have made some refactoring, the important part is, instead of doing different calculations on each type of Cursor placement on the core function, I made them just focus on the last character of the replacement made. This should be okay in most cases, then if the consuming end wants a customized placement of the cursor after the replacement, then they will compute it themselves and pass it onto the `getReplacement` function that is available rather than having a hard time on the generic function.

Also, I've made a refactor to separate the functions of each type as they calculate a bit differently on their own and I wanted them to be isolated and easily understandable.

With that, I have also tried to do a class-based approach, not sure if you would prefer it, but I believe there are some benefits, in some aspects. Such as passing the same parameters over and over again, etc., we can easily revert it though since I made it in a single commit. You can check the difference here https://github.com/dailydotdev/apps/pull/1820/commits/d627472c5db259d9981e1e8cd379ddf1e41ab643

2023-05-25 06:42 UTC, idoshamun commented on packages/shared/src/hooks/input/useMarkdownInput.ts
> +export const useMarkdownInput = ({
Please add `useMemo` according to the team guidelines

2023-05-25 06:43 UTC, idoshamun approved these changes
Please make sure to add `useMemo` before merging but we're all clear!

2023-05-25 07:43 UTC, sshanzel commented
> Please make sure to add useMemo before merging but we're all clear!

I have applied it now on the `mentions` property, but have kept the rest the same as they are already stable coming from a `useState` or `useQuery` 🥳 

The callbacks are left for now as they don't do heavy computations and are not yet referenced on any memoized values/components.

2023-05-25 07:59 UTC, idoshamun commented
@sshanzel I'm not sure about it but let's proceed for now. Once Chris/Ante are back let's discuss with them

2023-05-25 07:59 UTC, idoshamun approved these changes

2023-05-25 08:13 UTC, merged

2023-05-25 08:13 UTC, sshanzel commented
@capJavert @rebelchris Not urgent, just tagging for visibility regarding the useMemo when you get the time 🚢

2023-05-30 08:02 UTC, capJavert commented
Mentions `data` are already stable so memoizing them makes no difference. Analogy with `useState` is good since `useQuery` holds that data in state which changes only on refetch.

We do not need to memoize `useState` values because state itself only changes when updated which makes it stable. eg:

```js
  const [input, setInput] = useState(initialContent);
  
  const stableInput = useMemo(() => input, [input]); // this does nothing since `input` is already stable because it is state
```

If we were to add some computation for example if for some reason we used `filter` to include only some mentions then `useMemo` would be needed because `filter` would produce new array each time.

Same thing goes for `data ?? []` expression that was the last example here, `[]` would produce new array on each render as long as `data` is `undefined` so `useMemo` is valid option. ✅ 

We could however for this specific case just use `useQuery` `initialData: () => []` since we are only guarding from initial missing of data.

I would also memoize handlers like `onLinkCommand` with `useCallback` so that any other hook using those can memoize properly.