fix: typos in the code
dailydotdev/apps pull request #2052
Opened 2023-08-17 18:51 UTC by kavinkuma6

## Changes

### Describe what this PR does
- Fixes https://github.com/dailydotdev/daily/issues/960
- Fixes typos throughout the code

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?
- [x] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

2023-08-18 10:55 UTC, rebelchris requested changes
Thanks a lot for these fixes!
Just wondering what changed in the icon cases?

2023-08-18 10:55 UTC, rebelchris commented on packages/shared/src/components/icons/Bell/Notify/filled.svg
What changed in the icons?

2023-08-18 11:09 UTC, kavinkuma6 commented on packages/shared/src/components/icons/Bell/Notify/filled.svg
@rebelchris `id` has typo. Not a big deal though.
<img width="1096" alt="Screenshot 2023-08-18 at 4 39 09 PM" src="https://github.com/dailydotdev/apps/assets/24503078/c35ddab6-28a2-4643-83e8-2c61aed5e088">

2023-08-18 11:10 UTC, kavinkuma6 commented
@rebelchris also shall I add a pre commit hook to prevent typos in future? I think it is worth doing it.

2023-08-18 11:14 UTC, rebelchris commented on packages/shared/src/components/icons/Bell/Notify/filled.svg
Ah I see 🙏

2023-08-18 11:15 UTC, rebelchris approved these changes
Looks good to me, @sshanzel can you also review and potentially merge 🙏

As for your question, we don't really leverage pre-commit at the moment.
Perhaps if we can add it as a linting rule that would be cool. (Separate PR)

2023-08-21 10:03 UTC, sshanzel approved these changes
The build passed too! Looks great to me. Thank you so much for your contribution 🙏

2023-08-22 06:50 UTC, merged