fix: anchor tag inside anchor tag on squad shared post
dailydotdev/apps pull request #2205
Opened 2023-09-19 14:26 UTC by omBratteng

## Changes

### Describe what this PR does
- fix: anchor tag inside anchor tag on squad shared post
  Removes wrapping anchor tag and adds anchor tag for title and image

## Events

N/A

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

2023-09-19 15:33 UTC, rebelchris requested changes
Small fix needed

2023-09-19 15:33 UTC, rebelchris commented on packages/shared/src/components/post/SharePostContent.tsx
> +    <Link href={href} as={as}>
I think the target is missing from what it used to be.
For external is should be _blank

2023-09-19 15:33 UTC, rebelchris commented on packages/shared/src/components/post/SharePostContent.tsx
> +    <Link href={href} as={as}>
Same with rel

2023-09-20 08:20 UTC, rebelchris approved these changes
Good from my side, lets see what @capJavert says

2023-09-20 08:27 UTC, capJavert approved these changes
I think its fine for this case.

2023-09-20 08:27 UTC, merged