feat: add squad pinned posts reordering
dailydotdev/apps pull request #2299
Opened 2023-10-24 12:21 UTC by DragosIorgulescu

## Changes

- using the existing `updatePinPost` mutation

TODO:
- use a separate mutation for swapping
- agree on a long term solution

## Preview

![pinned-post-reordering](https://github.com/dailydotdev/apps/assets/1225100/b9ca189d-e36b-446f-bcf9-1e5f77c589fb)

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

2023-10-30 05:41 UTC, rebelchris requested changes
Nice work, very minor questions otherwise ok.

2023-10-30 05:41 UTC, rebelchris commented on packages/shared/src/components/Feed.tsx
> +    nextPost: (items[postMenuIndex + 1] as PostItem)?.post,
Oef not against the implementation, but thinking about a leanFeed, this is yet another constraint in moving it.

2023-10-30 05:41 UTC, rebelchris commented on packages/shared/src/graphql/posts.ts
> +    $prevPostId: ID
Do we need this change?

2023-11-06 09:00 UTC, sshanzel reviewed
Great work. Nothing blocking but we should maybe include the new icons on the index file of the folder itself.

2023-11-06 11:05 UTC, DragosIorgulescu commented on packages/shared/src/graphql/posts.ts
> +    $prevPostId: ID
good catch, removed ✂️

2023-11-06 11:13 UTC, DragosIorgulescu commented
> Great work. Nothing blocking but we should maybe include the new icons on the index file of the folder itself.

@sshanzel good point, however, does tree shaking drop any unused imports if exported the way these are in [index](https://github.com/dailydotdev/apps/blob/f5191754485e855f295539d2e1797672c88e19ca/packages/shared/src/components/icons/index.ts)?

2023-11-06 15:17 UTC, DragosIorgulescu commented
closing this here as I manually squash merged into main

2023-11-06 15:17 UTC, closed without merging