Fixed Indexing of button and Gradiant Image on Onboarding Extension Page
dailydotdev/apps pull request #2319
Opened 2023-10-30 18:37 UTC by Zainjaved96

The button on onboarding extension page was not clickable because gradiant image was on top of it. I simply indexed the image before button and it's good now.

## Changes

### Describe what this PR does
It just changed the indexes of image and button to make the button clickable and not hide behidn the image.
## Events

Did you introduce any new tracking events?
NO i did not
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
NO
- [ ] Have you done sanity checks in the extension?
NO
- [ ] Does this not break anything in companion?
NO

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)
NO it's simple indexing changes so no  media query was requried.

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android
NO
WT-{number} #done

2023-10-30 18:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dailydotdev/apps?pullRequest=2319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dailydotdev/apps?pullRequest=2319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dailydotdev/apps?pullRequest=2319) it.</sub>

2023-10-31 00:48 UTC, omBratteng approved these changes

2023-10-31 00:50 UTC, omBratteng requested changes
Thanks, just need to fix the order of the tailwind classnames, as tests are failing because of eslint erros.

```
packages/shared test:ci: > eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0
packages/shared test:ci: /home/circleci/project/packages/shared/src/components/ExtensionOnboarding.tsx
packages/shared test:ci:   28:11  warning  Invalid Tailwind CSS classnames order  tailwindcss/classnames-order
packages/shared test:ci:   36:9   warning  Invalid Tailwind CSS classnames order  tailwindcss/classnames-order
packages/shared test:ci: ✖ 2 problems (0 errors, 2 warnings)
packages/shared test:ci:   0 errors and 2 warnings potentially fixable with the `--fix` option.
packages/shared test:ci: ESLint found too many warnings (maximum: 0).
```

2023-10-31 06:04 UTC, rebelchris approved these changes
Oh thanks so much for this contribution.
If you could adjust the order/removal of z-0 we can proceed with merging.

2023-10-31 06:04 UTC, rebelchris commented on packages/shared/src/components/ExtensionOnboarding.tsx
> +          className="w-full btn-primary max-w-[18.75rem] z-1"
```suggestion
          className="z-1 w-full btn-primary max-w-[18.75rem]"
```

2023-10-31 06:04 UTC, rebelchris commented on packages/shared/src/components/ExtensionOnboarding.tsx
> +        className="absolute bottom-0 w-[33rem] z-0"
```suggestion
        className="absolute bottom-0 z-0 w-[33rem]"
```

Or: you don't really need the z-0 here though, it will work without.

2023-11-06 09:25 UTC, rebelchris approved these changes
Let's go :)

2023-11-06 09:36 UTC, merged