feat: ab test onboarding title and subtitle
dailydotdev/apps pull request #2389
Opened 2023-12-04 16:58 UTC by sshanzel

## Changes
- AB test the onboarding's both title and subtitle.
- As discussed during the meeting, the feature value should be what is expected as opposed to the usual values of v1, v2, etc.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-2018 #done

2023-12-04 17:11 UTC, rebelchris requested changes
1 small request 🙏

2023-12-04 17:11 UTC, rebelchris commented on packages/webapp/pages/onboarding.tsx
> +              Where developers {onboardingTitle} together
I suggest we put the entire title in the string not just the word.

2023-12-04 17:21 UTC, rebelchris approved these changes
Looks good to me.
@idoshamun anything from your side?

2023-12-05 07:31 UTC, idoshamun commented
@rebelchris can we make it one feature that returns both values? Otherwise experimentation will be much harder to set up.

2023-12-05 07:48 UTC, rebelchris commented
Ah good point forgot to add the check.
@sshanzel could you check if it supports json object with 2 strings for instance?

2023-12-05 10:44 UTC, capJavert approved these changes
Looks good from my end. Would love to see if json stuff works 👍

2023-12-05 10:51 UTC, sshanzel commented
Have applied the object structure for this feature with the key of `onboarding_copy`.

![Screenshot 2023-12-05 at 6 50 53 PM](https://github.com/dailydotdev/apps/assets/13744167/c49eec68-7e6f-4fad-a0aa-f5c5c44b4e1b)

2023-12-05 10:56 UTC, idoshamun approved these changes

2023-12-05 10:57 UTC, rebelchris approved these changes
Amazing amazing

2023-12-05 10:59 UTC, merged