chore: cleaning up copy link post page onboarding v3 and social proof onboarding experiment
dailydotdev/apps pull request #2804
Opened 2024-03-13 10:39 UTC by nensidosari

Slack threads testifying these are ok to cleanup:

- [Copy link](https://dailydotdev.slack.com/archives/C06K3QEFPE1/p1709659131058209?thread_ts=1709630063.617649&cid=C06K3QEFPE1) (won)
- [post page onboarding v3](https://dailydotdev.slack.com/archives/C02AA18RD1D/p1710187214094689) (lost)
- [social proof onboarding](https://dailydotdev.slack.com/archives/C06K5KAHM0X/p1708948319189189?thread_ts=1708933869.441869&cid=C06K5KAHM0X) (won)

2024-03-13 11:15 UTC, DragosIorgulescu approved these changes
just one non-blocking comment, otherwise, love seeing code removed ✂️

2024-03-13 11:15 UTC, DragosIorgulescu commented on packages/shared/src/components/Feed.tsx
> +  const lastShareMenuCloseTrackEvent = () => {};
is this variable still being used?

2024-03-13 11:54 UTC, rebelchris approved these changes
Cool just note Dragos comment, seems valid :)

2024-03-13 11:54 UTC, rebelchris commented on packages/shared/src/lib/featureManagement.ts
>      'post_page_onboarding',
Should this not also be removed then?

2024-03-13 11:54 UTC, rebelchris commented on packages/shared/src/lib/featureManagement.ts
>      'post_page_onboarding',
Oh has a follow up I guess?

2024-03-13 12:37 UTC, sshanzel requested changes
Looks great, just think we need more cleanup with the namings to avoid confusion.

2024-03-13 12:37 UTC, sshanzel commented on packages/shared/src/components/cards/ActionButtons.tsx
> +  const { onShareClick, post } = props;
Should we be updating this function? I think it is a bit confusing to say `onShareClick` when what it does is copy the link.

2024-03-13 12:37 UTC, sshanzel commented on packages/shared/src/components/cards/v1/ActionButtons.tsx
>  function ShareButton(props: ShareButtonProps) {
Same here, I don't think we should be calling this ShareButton when what it does now is copy. Would confuse devs who has no background to this.

2024-03-13 12:37 UTC, sshanzel commented on packages/shared/src/hooks/usePostContent.ts
> +  const onShare = () => copyLink(post);
Yep, this one too. We say `onShare` but we copy link 😅

2024-03-13 15:04 UTC, nensidosari commented
@sshanzel agree worth changing the naming, am doing that ATM but will be quite a lot of changes. So thinking of raising a separate PR for that.

2024-03-18 14:12 UTC, nensidosari commented
For the comments above @sshanzel created ticket, have started changes, have yet to finish them. In the meantime merging this PR.

2024-03-18 14:35 UTC, sshanzel approved these changes
Looks great to me! 🚀

2024-03-18 14:47 UTC, merged