fix: adjust discussed feed styles to match new mobile UX
dailydotdev/apps pull request #2894
Opened 2024-04-01 10:57 UTC by DragosIorgulescu

## Changes

## Events

N / A

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-252

2024-04-01 14:16 UTC, sshanzel commented on packages/shared/src/components/CommentFeed.tsx
> -          isNewMobileLayout && isMainFeed && 'px-4',
What should this look like in control values? Can you also attach screenshot of the old UI? Just to make sure everything still looks normal.

2024-04-01 14:16 UTC, sshanzel approved these changes
Looks great. Kindly verify that the control still looks normal, we should be good here :shipit:

2024-04-01 16:00 UTC, sshanzel requested changes
Sorry for the late request, I think the labels on the navigation for tablet is a bit bigger than expected.

2024-04-02 09:27 UTC, DragosIorgulescu commented
> Sorry for the late request, I think the labels on the navigation for tablet is a bit bigger than expected.

@sshanzel not sure what you are referring to, could you elaborate? Which labels?

2024-04-02 09:30 UTC, sshanzel commented
@DragosIorgulescu hi, sorry for the lack of clarity. These ones. In the Figma they're at `typo-caption2`, after inspecting the element, I think they're on `typo-callout`.

![Screenshot 2024-04-02 at 5 28 59 PM](https://github.com/dailydotdev/apps/assets/13744167/9f95b9da-313e-4439-96a2-0c28c9f89077)

2024-04-02 10:15 UTC, DragosIorgulescu commented
> @DragosIorgulescu hi, sorry for the lack of clarity. These ones. In the Figma they're at typo-caption2, after inspecting the element, I think they're on typo-callout.

@sshanzel thank you for the clarification 🙏  I updated this, however to me these look way tinier than designs now (even though I agree these are specified with `typo-caption2` there. See below

<img width="877" alt="Screenshot 2024-04-02 at 13 14 25" src="https://github.com/dailydotdev/apps/assets/1225100/894bd4c7-d08c-4a08-aa56-fdc362145f42">

This feels like we should use `typo-caption1` rather 🤔

2024-04-02 10:21 UTC, sshanzel commented
> This feels like we should use typo-caption1 rather

Yep, totally agree with this. Sometimes it really looks different from Figma, I think what you suggested it the sweet spot.

2024-04-02 10:22 UTC, sshanzel approved these changes
Feel free to change it to `typo-caption1` - got nothing more on this, looks amazing! :shipit:

2024-04-02 10:49 UTC, merged