feat: implement public squad submit for review modal
dailydotdev/apps pull request #3092
Opened 2024-05-10 15:37 UTC by kopancek

## Changes

Added modal for submitting public squad for review.
Right now the submit button is not doing anything, as is specified in the task itself:
https://dailydotdev.atlassian.net/browse/MI-339

### Screenshots

<img width="428" alt="Screenshot 2024-05-10 at 17 25 54" src="https://github.com/dailydotdev/apps/assets/9974711/a62ac8d5-9435-411f-af20-7a021c44c788">
<img width="427" alt="Screenshot 2024-05-10 at 17 26 03" src="https://github.com/dailydotdev/apps/assets/9974711/acdeaec5-282c-4f9e-910c-5a98c97f3c93">
<img width="415" alt="Screenshot 2024-05-10 at 17 36 07" src="https://github.com/dailydotdev/apps/assets/9974711/02e8cc2c-243b-4723-9afe-9b424d2b2397">

## Manual Testing

### On those affected packages:
- [X] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [X] MobileL (420px)
- [X] Tablet (656px)
- [X] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-339 #done

2024-05-13 11:32 UTC, rebelchris requested changes
Looks pretty good to me
Just the link should probably be blank and have rels if this the case.


Also maybe check if there should be a tooltip on the disabled button (it's something we used to do a lot)

2024-05-13 11:32 UTC, rebelchris commented on packages/shared/src/components/icons/index.ts
> -export * from './ClockPending';
What was this before?

2024-05-13 11:32 UTC, rebelchris commented on packages/shared/src/components/modals/squads/SubmitSquadForReviewModal.tsx
> +              href="https://docs.daily.dev/docs/for-content-creators/content-guidelines"
I assume this should be targeting blank? (but maybe double check)

2024-05-13 11:32 UTC, rebelchris commented on packages/shared/src/components/modals/squads/SubmitSquadForReviewModal.tsx
> +  'flex flex-col gap-5 p-5 -my-2.5 rounded-16 bg-theme-float typo-callout',
Personally don't like this as it looks like a bug (raised on slack)

2024-05-14 07:17 UTC, nensidosari approved these changes
Looks good

2024-05-14 08:54 UTC, rebelchris approved these changes

2024-05-14 13:14 UTC, merged