fix: add black icon for pwa;
dailydotdev/apps pull request #3427
Opened 2024-08-05 14:27 UTC by ilasw

## Changes

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

2024-08-06 08:29 UTC, omBratteng approved these changes
Run them through https://tinypng.com/ to reduce the size about ~75%

2024-08-06 08:30 UTC, omBratteng requested changes
Run them through [tinypng.com](https://tinypng.com/) to reduce the size about ~75%

2024-08-06 11:29 UTC, nensidosari commented on packages/webapp/public/android-chrome-192x192.png
Just checking, do these need to be rounded again?

2024-08-06 12:50 UTC, ilasw commented on packages/webapp/public/android-chrome-192x192.png
Seems to be rounded by device: 

iOS
![image](https://github.com/user-attachments/assets/1a4b0630-240b-4444-bb0f-4d52a4af962b)

Android
![telegram-cloud-photo-size-4-5877356178856592093-x](https://github.com/user-attachments/assets/5548641c-b9fb-489b-bb0d-50ca3466e9cc)

2024-08-06 13:11 UTC, nensidosari approved these changes
Code looks good, but I'm not able to test through the preview domain. What is wrong with it?

2024-08-06 15:21 UTC, nensidosari commented
> Don't know, I'm using this link to test it: https://daily-webapp-git-mi-468-change-app-icon-back-396b32-dailydotdev.vercel.app/

@ilasw but the app doesn't load with this link, I see just a blank page

2024-08-06 16:01 UTC, ilasw commented
@nensidosari I know, but subdomain.daily.dev won't render :| It happened before for long branch names.
I can try to create a new short branch and see if it works. What do you think?

2024-08-06 17:02 UTC, sshanzel approved these changes
Looks amazing to me.

2024-08-07 08:49 UTC, nensidosari commented
@ilasw no problem, not a big change here so not necessary. U can proceed with merging 🙌

2024-08-07 19:48 UTC, omBratteng commented
> > Don't know, I'm using this link to test it: [daily-webapp-git-mi-468-change-app-icon-back-396b32-dailydotdev.vercel.app](https://daily-webapp-git-mi-468-change-app-icon-back-396b32-dailydotdev.vercel.app/)
> 
> @ilasw but the app doesn't load with this link, I see just a blank page

Seems like Vercel is stuck at generating SSL

2024-08-07 19:56 UTC, omBratteng commented
I've manually changed the preview domain, so it should work now

2024-08-08 08:29 UTC, ilasw commented
thanks @omBratteng ! Now it works 💯

2024-08-08 10:48 UTC, merged