fix: move to next 14 🫶🏻
dailydotdev/apps pull request #3520
Opened 2024-09-06 12:11 UTC by rebelchris

## Changes

🥁  Next 14 upgrade 🥁  

Seems to works fine now :) 
Not sure if they themselves fixed the SVGR issue in the last release, but seems stable now.

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

2024-09-06 12:13 UTC, omBratteng approved these changes
YOLO 🦾
(Change wise it looks good)

Should perhaps also test in preview

2024-09-06 12:40 UTC, capJavert commented on packages/shared/package.json
> +    "next": "14.2.8",
Probably not just next but main bundle jumped by ~19kb https://vercel.com/dailydotdev/daily-webapp/8bvbNVp4a3bn1sG6wYfkv5W6nKpr#L157 vs main, something to maybe take a look at

2024-09-09 12:42 UTC, capJavert commented on packages/shared/package.json
> +    "next": "14.2.8",
https://github.com/vercel/next.js/issues/58047

2024-09-09 13:13 UTC, capJavert approved these changes
Changes wise nothing crucial, good work on this 💪

2024-09-09 13:13 UTC, capJavert commented on packages/webapp/next.config.js
> -        },
Removed accidentally?

2024-09-09 13:15 UTC, rebelchris commented on packages/webapp/next.config.js
> -        },
Oh weird didn't need to indeed :O

2024-09-09 16:16 UTC, sshanzel approved these changes
Santa gave gifts early this year 😂 

Great work on the surprise upgrade 💪

2024-09-09 23:59 UTC, omBratteng requested changes

2024-09-09 23:59 UTC, omBratteng commented on packages/extension/package.json
> +    "next": "14.2.8",
```suggestion
    "next": "14.2.9",
```
New version just dropped

2024-09-10 08:40 UTC, nensidosari approved these changes
Looks great!! Tested in preview as well and couldn't find any issue.

2024-09-10 08:47 UTC, omBratteng approved these changes

2024-09-10 09:36 UTC, merged