#1469 issue solved by @ashish-maurya531
dailydotdev/apps pull request #3650
Opened 2024-10-10 07:41 UTC by ashish-maurya531

#1469 BUG: Unable to scroll in Search suggestions dropdown issue fixed

2024-10-10 07:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dailydotdev/apps?pullRequest=3650) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dailydotdev/apps?pullRequest=3650) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dailydotdev/apps?pullRequest=3650) it.</sub>

2024-10-10 10:43 UTC, sshanzel requested changes
Thank you so much for your effort, kindly check the comments, then I think we should be good to go after running some tests.

2024-10-10 10:43 UTC, sshanzel commented on packages/shared/src/components/search/SearchBarSuggestionList.tsx
> +}
We should not need the extra space.
```suggestion
}
```

2024-10-10 10:43 UTC, sshanzel commented on packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
> +
Same goes here, otherwise the lint might produce an error.
```suggestion
```

2024-10-10 10:43 UTC, sshanzel commented on packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
> +
Same goes here, otherwise the lint might produce an error.
```suggestion
```

2024-10-10 10:43 UTC, sshanzel commented on packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
> +                'absolute w-full items-center rounded-b-16 border-0 border-border-subtlest-tertiary bg-background-default px-3 py-2 laptop:h-auto laptop:border-x laptop:border-b laptop:bg-background-
Through tailwind, we should be able to apply the styles.
```suggestion
                'absolute w-full items-center rounded-b-16 border-0 border-border-subtlest-tertiary bg-background-default px-3 py-2 laptop:h-auto laptop:border-x laptop:border-b laptop:bg-background-subtle laptop:shadow-2 overflow-y-auto max-h-[30rem]'
```

2024-10-10 10:43 UTC, sshanzel commented on packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
> +              style={{ maxHeight: '450px', overflowY: 'auto' }}
As suggested above, let's use tailwind 🙏 
```suggestion
```

2024-10-10 11:17 UTC, ashish-maurya531 commented
@sshanzel Commited desired changes

2024-10-10 12:11 UTC, sshanzel commented
> @sshanzel Commited desired changes

One last thing is to fix the lint issues then we should be able to merge 🥳 

Reference: https://app.circleci.com/pipelines/github/dailydotdev/apps/20565/workflows/2a096abb-2a1d-4509-a725-b14286a74f29/jobs/56103

2024-10-10 13:49 UTC, sshanzel approved these changes
Looks good to me! 🥳 

Thank you for the contribution 💪

2024-10-10 14:04 UTC, ashish-maurya531 commented
@sshanzel you have merged 
but i not able to find myself in list of contributers.

2024-10-10 14:07 UTC, ashish-maurya531 commented
@sshanzel 
![image](https://github.com/user-attachments/assets/633aa179-afb5-4ca2-9020-b8e18313da13)

2024-10-11 08:06 UTC, rebelchris approved these changes
Worth a try, probably best to monitor on deployment also for mobile.

2024-10-12 09:59 UTC, ashish-maurya531 commented
@omBratteng @ilasw @capJavert @nensidosari @AmarTrebinjac  request to approve changes.

2024-10-13 03:29 UTC, sshanzel commented on packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
> +            <div className="absolute max-h-[30rem] w-full items-center overflow-y-auto rounded-b-16 border-0 border-border-subtlest-tertiary bg-background-default px-3 py-2 laptop:h-auto laptop:borde
The fix should actually be on laptop only as discussed with the design team.

```suggestion
            <div className="absolute laptop:max-h-[30rem] w-full items-center overflow-y-auto rounded-b-16 border-0 border-border-subtlest-tertiary bg-background-default px-3 py-2 laptop:h-auto laptop:border-x laptop:border-b laptop:bg-background-subtle laptop:shadow-2">
```

2024-10-13 03:30 UTC, sshanzel commented
> thank You @sshanzel on beginner level it is great to contribute in big project. This was my 1st project to contribute.

That's great to hear! I will merge this later today and soon you will see the contributor badge 😍

2024-10-13 11:36 UTC, ashish-maurya531 reviewed
great

2024-10-14 06:09 UTC, rebelchris requested changes

2024-10-14 06:09 UTC, rebelchris commented on packages/shared/.eslintrc.js
> +  },
This shouldn't be needed and should be reverted 🙏

2024-10-14 06:46 UTC, sshanzel commented on packages/shared/.eslintrc.js
> +  },
```suggestion
```

2024-10-14 06:56 UTC, rebelchris approved these changes

2024-10-14 07:23 UTC, sshanzel commented
Looked amazing 🤩 

<img width="570" alt="Screenshot 2024-10-14 at 11 21 38 AM" src="https://github.com/user-attachments/assets/49818ce5-8571-49f5-8d7a-0eb74b3515e2">

2024-10-14 08:55 UTC, merged

2024-10-14 09:03 UTC, ashish-maurya531 commented
@sshanzel thanks 👍