refactor: report modal to reason selection modal
dailydotdev/apps pull request #3656
Opened 2024-10-10 09:55 UTC by sshanzel

## Changes
- Renamed report modal to reason selection modal. This modal is also used for reporting post/comment/source. 

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

2024-10-11 08:11 UTC, rebelchris commented on packages/shared/src/components/modals/common.tsx
> +const ReasonSelectionModal = dynamic(
RejectionReasonModal would make more sense indeed :)

2024-10-11 08:11 UTC, rebelchris requested changes
Agree with Nensi :)

2024-10-13 01:39 UTC, sshanzel commented on packages/shared/src/components/modals/common.tsx
> +const ReasonSelectionModal = dynamic(
> Renamed report modal to reason selection modal. This modal is also used for reporting post/comment/source.

Yes, like mentioned, this is used also for other reasons.

2024-10-14 06:08 UTC, rebelchris approved these changes

2024-10-14 06:41 UTC, merged