fix: set min width and max width to fit top reader widget
dailydotdev/apps pull request #3795
Opened 2024-11-13 17:02 UTC by omBratteng

## Changes

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

2024-11-14 06:13 UTC, rebelchris requested changes
Maybe we should add truncate just to be safe on possible lengthy tags?
![Screenshot 2024-11-14 at 08 13 14](https://github.com/user-attachments/assets/94088211-7107-4b97-b344-2605d2776a0a)

2024-11-15 15:34 UTC, omBratteng commented
![image](https://github.com/user-attachments/assets/636ac6e4-f68d-48cf-ae5a-57d4574adb13)

2024-11-19 08:51 UTC, sshanzel approved these changes

2024-11-19 14:34 UTC, AmarTrebinjac approved these changes

2024-11-21 07:03 UTC, rebelchris approved these changes

2024-11-21 07:18 UTC, merged