fix: review QA
dailydotdev/apps pull request #669
Opened 2021-11-05 15:01 UTC by rebelchris

Feedback round from QA session.

- New blocked tag layout
- Passing from the sidebar down
- Empty tag state filter

DD-299 #done

2021-11-07 16:25 UTC, rebelchris commented
@idoshamun If you have time, could you check this refactor work? 🤗

2021-11-08 07:21 UTC, idoshamun requested changes
Please check my comments

2021-11-08 07:21 UTC, idoshamun commented on packages/shared/src/components/Sidebar.tsx
> +  };
Isn't it redundant? Why don't you use `setUnblockItem` directly?

2021-11-08 07:21 UTC, idoshamun commented on packages/shared/src/components/filters/CategoryButton.tsx
> +  onUnfollowTags?: (tags, category?) => void;
Function arguments don't have types here

2021-11-08 07:21 UTC, idoshamun commented on packages/shared/src/components/filters/TagButton.tsx
> +  onUnblockTags?: (tags) => void;
Functions here don't have types for their arguments

2021-11-08 07:21 UTC, idoshamun commented on packages/shared/src/components/filters/TagCategoryDropdown.tsx
> +  onUnblockTags?: (tags) => void;
Functions arguments don't have types

2021-11-08 07:21 UTC, idoshamun commented on packages/shared/src/components/filters/TagItemList.tsx
> +  onUnblockTags?: (tags) => void;
No types

2021-11-08 12:00 UTC, rebelchris commented
@idoshamun Added types :)

2021-11-08 12:33 UTC, idoshamun approved these changes
Perfect!

2021-11-08 12:50 UTC, merged