feat: customize modal
dailydotdev/apps pull request #708
Opened 2021-11-30 08:14 UTC by rebelchris

We decided to move the customisation for the feed to it's own modal.

This is as a separate pre-work task for the re layout.

<img width="1095" alt="Screenshot 2021-11-30 at 12 13 45" src="https://user-images.githubusercontent.com/554874/144009885-1f555741-ef74-4444-a5f4-329d1c54d607.png">

2021-11-30 12:06 UTC, idoshamun requested changes
Please check my comments and also fix the PR title to be more explicit :)

2021-11-30 12:06 UTC, idoshamun commented on packages/shared/src/components/Settings.tsx
>    const Section = useMemo(
This can go outside now that it is not dependent on any variable

2021-11-30 12:06 UTC, idoshamun commented on packages/shared/src/components/Settings.tsx
> +  const SectionTitle = classed(
This can go outside now that it is not dependent on any variable

2021-11-30 12:06 UTC, idoshamun commented on packages/shared/src/components/modals/FeedSettingsModal.tsx
> +);
We don't need to import it dynamically

2021-12-01 05:54 UTC, rebelchris commented
@idoshamun Thanks! that even seems to have fixed the testing issue 😂
Also refactored to include Lee's amazing tooltip 🤘

2021-12-01 05:56 UTC, idoshamun approved these changes
Woohoo!

2021-12-01 06:01 UTC, merged