fix: window is not defined yet on shareable link
dailydotdev/apps pull request #754
Opened 2021-12-22 16:41 UTC by sshanzel

When `window` is not yet defined, the shareable link can't be fetched yet.

2021-12-22 16:44 UTC, idoshamun requested changes
Great catch! But actually `windowLoaded` is used for deferred loading of resources. The best approach here is to check if `window` is defined. Also I encourage you to add this check into the function itself

2021-12-22 16:47 UTC, sshanzel commented
That makes sense since it is a function we can ensure the value returned will be what is expected.

2021-12-22 16:55 UTC, sshanzel commented
That makes sense since it is a function we can ensure the value returned will be what is expected.

I have tried to check if `window` exists but it seems to fail still. So now I just enclosed it with a try-catch to ensure workability.

2021-12-22 17:02 UTC, idoshamun commented
The undefined test should work. I think we test it using typeof try looking for it in the codebase

2021-12-22 17:08 UTC, sshanzel commented
Unfortunately, it is not working. I think it is because the static props are running without the context of browser or window and just running as JS which could be why the error displayed is coming from the static props.

I also tried `window === undefined` but it still gives the error.

![image](https://user-images.githubusercontent.com/13744167/147129472-381db1f4-f82b-4be8-9156-7fa54f788677.png)

2021-12-22 17:25 UTC, idoshamun commented
Something doesn't make sense to me because it shouldn't fail if you make sure this is true:
`typeof window !== 'undefined'`

2021-12-22 17:57 UTC, sshanzel commented
I am actually confused as well. I have tried different variations and all other cases to see what will happen. This is actually the first time I encountered `window` is not even recognized to be checked.

![image](https://user-images.githubusercontent.com/13744167/147135121-93ab6101-d75e-4b82-acdd-ff07544be476.png)

2021-12-22 22:37 UTC, idoshamun commented
You're missing the quotes on the type check. It should be `'undefined'`

2021-12-23 03:25 UTC, sshanzel commented
Oh, wow. It was just a matter of quotes 😆  

Quick link: https://daily-webapp-mg6d9eswa-dailydotdev.vercel.app/posts/_xOdpqEBi

2021-12-23 03:30 UTC, rebelchris approved these changes
NICE! 👏

2021-12-23 06:21 UTC, idoshamun approved these changes
Woohoo!

2021-12-23 06:27 UTC, merged