[fix] Changed the Background color of the MostVisited websites 🎨
dailydotdev/apps pull request #856
Opened 2022-01-27 03:24 UTC by Keshraf

2022-01-27 07:21 UTC, rebelchris commented
@Keshraf Wow thanks a lot for putting in the work here 💪

We do have a in-house designer and quite a strict guideline for branding, these colors are not brand specified, but I've asked him to see if we should change this section based on your PR.

For future reference, when it comes to design related tasks its best to open a discussion or issue first.

Nevertheless thank you for your willingness and making the product better 💖

2022-01-27 11:00 UTC, rebelchris requested changes
Hi @Keshraf ,

Thanks again for this great suggestion.
Our designer agrees that adding the border is a great addition.

However it should be our brand guideline colors (secondary)
See suggested fix.

2022-01-27 11:00 UTC, rebelchris commented on packages/extension/src/newtab/MostVisitedSites.tsx
> +                'focus-outline w-8 h-8 rounded-lg overflow-hidden bg-[#0E1217] border-[#2D323B]',
Asked our designed and he suggests to use the `secondary-divider` color.
You can use it like so:

```suggestion
                'focus-outline w-8 h-8 rounded-lg overflow-hidden border border-theme-divider-secondary',
```

2022-01-27 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dailydotdev/apps?pullRequest=856) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dailydotdev/apps?pullRequest=856) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dailydotdev/apps?pullRequest=856) it.</sub>

2022-01-28 12:42 UTC, rebelchris approved these changes
Nice work, this looks great 👏

2022-01-31 06:01 UTC, rebelchris commented
@Keshraf we recently had some changed in this file because of a new way of using it.
Would you mind resolving the issues 🙏

2022-01-31 08:09 UTC, closed without merging

2022-01-31 08:11 UTC, rebelchris commented
@Keshraf Sorry I meant to resolve the merge conflict issue if you would still like to help with this issue 🙏

2022-01-31 08:13 UTC, Keshraf commented
@rebelchris Thank you for clarifying 😅. I would love to work on it.