refactor: text field guideline update
dailydotdev/apps pull request #858
Opened 2022-01-27 16:31 UTC by sshanzel

## Changes

The primary change to look for is the variation of the font colors based on which `fieldType` the input is. The `tertiary` is a new addition that is used already in the custom links so there are no pre-existing implementations of it.

The `compact` property is now gone and was replaced by being the `secondary` field type.

Primary is the common and default implementation of the text field.

This now supports icons inside the text field itself and the padding varies between having one or not.

## Testing

- Did you introduce testing for this PR
- ☑️ Did you test the webapp? **Yes**
- ☑️ Did you test the extension? **Yes**

DD-495 #done

**Note:** just waiting for Tsahi's answer regarding the right icon but this should be alright to be reviewed.

2022-01-28 12:41 UTC, rebelchris requested changes
Very nice setup!
Would only state we could add some more tests around the specific types?

Perhaps we can add to check for certain classes?
This will quickly show us if we ever move one by accident

What do you think?

2022-01-28 12:41 UTC, rebelchris commented on packages/shared/src/components/fields/TextField.spec.tsx
>  it('should show both label and placeholder in compact mode', async () => {
Can we rename this to `secondary` mode? (The actual test)

2022-01-28 12:41 UTC, rebelchris commented on packages/shared/src/components/fields/TextField.spec.tsx
>  it('should show both label and placeholder in compact mode', async () => {
Also can we add a specific test for this new one?

2022-01-28 12:41 UTC, rebelchris commented on packages/shared/src/components/fields/TextField.tsx
> +  const isTertiary = fieldType === 'tertiary';
Could we maybe make this a bit more explicit?

2022-01-31 07:17 UTC, sshanzel commented
@rebelchris thank you for the review! Totally agree with it! This is a reused component across the app, tests must be very strict in this scenario.

2022-01-31 13:48 UTC, rebelchris approved these changes
Nice work on this

2022-02-01 06:17 UTC, idoshamun reviewed
Awesome!

2022-02-03 10:16 UTC, merged