feat: add dynamic signup button color
dailydotdev/apps pull request #911
Opened 2022-03-01 09:05 UTC by ayadotdev

## Changes

This PR adds dynamic signup button color class.

![Screenshot 2022-03-01 at 09 56 38](https://user-images.githubusercontent.com/33021204/156137638-c8ccdd0c-af5c-44b1-b41b-6e7af6a3dc23.png)

## Manual Testing

- On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?

DD-407 #done

2022-03-01 09:38 UTC, rebelchris requested changes
Awesome, looks great just two minor changes and we should be ready to go

2022-03-01 09:38 UTC, rebelchris commented on packages/shared/src/components/LoginButton.tsx
> +      className={classNames('btn-primary', className, buttonColor.button)}
This buttonColor should actually overwrite the btn-primary, else we have contradicting classes.

2022-03-01 09:38 UTC, rebelchris commented on packages/shared/src/lib/featureManagement.ts
> +  );
Think about this, something I forgot to mention is that we now also have `validOptions` as the third parameter here.
This should be an array of the options we allow to be valid.

```suggestion
  static readonly SignupButtonColor = new Features(
    'signup_button_theme_color',
    'primary',
    [
    'primary',
    'color1',
    'color2',
  ]
  );
```

2022-03-01 14:15 UTC, rebelchris approved these changes
Nice work!
@sshanzel Would you mind having a look before we merge

2022-03-03 01:55 UTC, sshanzel approved these changes
Looks perfect to my eyes! 🤩 🚢

2022-03-03 11:39 UTC, merged