refactor: add tldr summary to seo description plus test
dailydotdev/apps pull request #940
Opened 2022-03-29 14:29 UTC by ayadotdev

## Changes

### Describe what this PR does

This PR adds a TLDR summary to the seo description.

### **Please make sure existing components are not breaking/affected by this PR**

## Manual Testing

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

DD-520 #done

2022-03-30 05:54 UTC, rebelchris requested changes
Nice work!
Some small things, but great setup 💖

2022-03-30 05:54 UTC, rebelchris commented on packages/webapp/__tests__/PostPage.tsx
> +it('should check meta tag', async () => {
I would name these a bit more explicit as:
"should check meta tag with only summary"

2022-03-30 05:54 UTC, rebelchris commented on packages/webapp/__tests__/PostPage.tsx
> +it('should check meta tag', async () => {
"should check meta tag with only description"

2022-03-30 05:54 UTC, rebelchris commented on packages/webapp/__tests__/PostPage.tsx
> +it('should check meta tag', async () => {
"should check meta tag with no description and summary"

2022-03-30 05:54 UTC, rebelchris commented on packages/webapp/__tests__/PostPage.tsx
> +
Also we should probably add one with both summary and description to make sure it favours the summary.

2022-03-30 05:54 UTC, rebelchris commented on packages/webapp/pages/posts/[id].tsx
> +  if (post?.description) {
Why don't we check for length here?
Could you try with a empty description object and see what happens?

2022-03-30 05:54 UTC, rebelchris commented on packages/webapp/pages/posts/[id].tsx
> +        <NextSeo data-testId="post-page-seo-id" {...seo} />
You can remove the testId here.

2022-03-30 10:06 UTC, ayadotdev commented on packages/webapp/pages/posts/[id].tsx
> +        <NextSeo data-testId="post-page-seo-id" {...seo} />
All seems done, thank you! @rebelchris

2022-03-30 10:07 UTC, ayadotdev commented
All seems done, thank you! @rebelchris

2022-03-30 11:13 UTC, rebelchris approved these changes
Looks great! thanks on these changes
Was the length check needed?

2022-03-31 07:28 UTC, sshanzel approved these changes
Great work on this! 🙌

2022-05-03 13:36 UTC, rebelchris approved these changes
Think we are ready to go here 💖

2022-05-17 09:13 UTC, merged